# Generated by Django 6.0.4 on 2026-04-13 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_exportlog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Tên danh mục, tối thiểu 2 ký tự', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Giá cơ bản, không được âm', max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(help_text='Đơn vị gốc (Bao, Cây, m3...)', max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL hình ảnh (phải là URL hợp lệ)', max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Tên sản phẩm, tối thiểu 2 ký tự', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Tỉ lệ chuyển đổi, phải > 0', max_digits=19, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit_name',
            field=models.CharField(help_text='Tên đơn vị (Bao, Cây, m3...)', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
