# Generated by Django 6.0.3 on 2026-04-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_warehousetransaction_warehouse_and_more'),
        ('warehouse', '0002_exportreceipt_exportreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreceipt',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_receipts', to='order.salesorder'),
        ),
    ]
