# Generated by Django 6.0.4 on 2026-04-13 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_warehousetransaction_warehouse_and_more'),
        ('warehouse', '0004_remove_exportreceipt_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreceipt',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Đơn hàng liên quan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_receipts', to='order.salesorder'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số lượng đang giữ cho đơn hàng chờ xuất', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exportreceiptitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Số lượng, phải > 0', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='exportreceiptitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Giá/đơn vị, không được âm', max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='importreceiptitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Số lượng, phải > 0', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='importreceiptitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Giá/đơn vị, không được âm', max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số lượng tồn, không được âm', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
