# Generated by Django 6.0.4 on 2026-05-07 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_exportreceipt_pickup_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportreceipt',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Chờ lấy hàng'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='exportreceiptitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='So luong, phai > 0', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='exportreceiptitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Gia/don vi, khong duoc am', max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='importreceipt',
            name='note',
            field=models.TextField(blank=True, help_text='Thu kho ghi chu khi tao', null=True),
        ),
        migrations.AlterField(
            model_name='importreceipt',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Ke toan ghi ly do tu choi', null=True),
        ),
        migrations.AlterField(
            model_name='importreceiptitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='So luong, phai > 0', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='importreceiptitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Gia/don vi, khong duoc am', max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số lượng tồn không được âm', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
