# Generated by Django 6.0.4 on 2026-04-13 04:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_category_name_alter_product_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_code', models.CharField(db_index=True, help_text='Mã phiên kiểm kê, VD: KK-20260413-001', max_length=30, unique=True)),
                ('audit_date', models.DateField(db_index=True, help_text='Ngày thực hiện kiểm kê')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Đang kiểm'), ('SUBMITTED', 'Đã nộp – chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELLED', 'Hủy')], db_index=True, default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audits_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên kiểm kê',
                'verbose_name_plural': 'Phiên kiểm kê',
                'db_table': 'inventory_audits',
                'ordering': ['-audit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='Snapshot tồn kho hệ thống TẠI THỜI ĐIỂM tạo phiên kiểm kê', max_digits=15)),
                ('actual_quantity', models.DecimalField(decimal_places=2, help_text='Số lượng thực tế đếm được — do KHO nhập', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryaudit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Dòng kiểm kê',
                'verbose_name_plural': 'Dòng kiểm kê',
                'db_table': 'inventory_audit_items',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLoss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loss_code', models.CharField(db_index=True, help_text='Mã phiếu hao hụt, VD: HH-20260413-001', max_length=30, unique=True)),
                ('loss_quantity', models.DecimalField(decimal_places=2, help_text='Số lượng hao hụt — luôn dương', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('loss_type', models.CharField(choices=[('DAMAGE', 'Hư hỏng / Vỡ vụn'), ('SHRINKAGE', 'Hao hụt tự nhiên (bay hơi, khô, co ngót)'), ('EXPIRED', 'Hết hạn sử dụng'), ('THEFT', 'Mất mát / Trộm cắp'), ('OTHER', 'Khác')], db_index=True, default='OTHER', max_length=10)),
                ('loss_reason', models.TextField(help_text='Mô tả chi tiết nguyên nhân hao hụt')),
                ('loss_date', models.DateField(db_index=True, help_text='Ngày phát sinh hao hụt')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='Giá vốn/đơn vị tại thời điểm hao hụt — snapshot từ Product.base_price', max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], db_index=True, default='PENDING', max_length=10)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_item', models.OneToOneField(blank=True, help_text='Dòng kiểm kê phát sinh hao hụt (null nếu tạo thủ công)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_record', to='inventory.inventoryaudititem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_records_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_records', to='product.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_records_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu hao hụt',
                'verbose_name_plural': 'Phiếu hao hụt',
                'db_table': 'inventory_losses',
                'ordering': ['-loss_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('STOCK_SUMMARY', 'Tổng hợp tồn kho'), ('IMPORT_HISTORY', 'Lịch sử nhập kho'), ('EXPORT_HISTORY', 'Lịch sử xuất kho'), ('LOSS_REPORT', 'Báo cáo hao hụt'), ('AUDIT_REPORT', 'Báo cáo kiểm kê'), ('DISCREPANCY', 'Báo cáo chênh lệch kho')], db_index=True, max_length=20)),
                ('export_format', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('PDF', 'PDF')], max_length=5)),
                ('exported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filter_params', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký xuất báo cáo',
                'verbose_name_plural': 'Nhật ký xuất báo cáo',
                'db_table': 'report_export_logs',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['audit_date', 'status'], name='idx_audit_date_status'),
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['approved_by'], name='idx_audit_approved_by'),
        ),
        migrations.AddIndex(
            model_name='inventoryaudititem',
            index=models.Index(fields=['product'], name='idx_audit_item_product'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaudititem',
            constraint=models.CheckConstraint(condition=models.Q(('actual_quantity__gte', 0)), name='chk_audit_item_actual_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaudititem',
            constraint=models.CheckConstraint(condition=models.Q(('system_quantity__gte', 0)), name='chk_audit_item_system_qty_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryaudititem',
            unique_together={('audit', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventoryloss',
            index=models.Index(fields=['loss_type', 'status'], name='idx_loss_type_status'),
        ),
        migrations.AddIndex(
            model_name='inventoryloss',
            index=models.Index(fields=['loss_date', 'product'], name='idx_loss_date_product'),
        ),
        migrations.AddIndex(
            model_name='inventoryloss',
            index=models.Index(fields=['product', 'status'], name='idx_loss_product_status'),
        ),
        migrations.AddConstraint(
            model_name='inventoryloss',
            constraint=models.CheckConstraint(condition=models.Q(('loss_quantity__gt', 0)), name='chk_loss_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryloss',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='chk_loss_unit_cost_non_negative'),
        ),
        migrations.AddIndex(
            model_name='reportexportlog',
            index=models.Index(fields=['report_type', 'exported_at'], name='idx_exportlog_type_date'),
        ),
        migrations.AddIndex(
            model_name='reportexportlog',
            index=models.Index(fields=['exported_by'], name='idx_exportlog_user'),
        ),
    ]
