# Generated by Django 6.0.4 on 2026-04-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='reportexportlog',
                    name='idx_exportlog_type_date',
                ),
                migrations.RemoveIndex(
                    model_name='reportexportlog',
                    name='idx_exportlog_user',
                ),
                migrations.DeleteModel(
                    name='ReportExportLog',
                ),
            ],
            database_operations=[],
        ),
    ]
