# Generated by Django 6.0.3 on 2026-04-02 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdebt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_debts', to='order.salesorder'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
    ]
