# Generated by Django 6.0.4 on 2026-05-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_salesorder_picked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Đã xác nhận'), ('WAITING', 'Chờ lấy hàng'), ('PICKED', 'Đã lấy hàng'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã huỷ')], default='CONFIRMED', max_length=15),
        ),
    ]
