# Generated by Django 6.0.4 on 2026-04-20 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ReportExportLog',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('report_type', models.CharField(choices=[('STOCK_SUMMARY', 'Tổng hợp tồn kho'), ('IMPORT_HISTORY', 'Lịch sử nhập kho'), ('EXPORT_HISTORY', 'Lịch sử xuất kho'), ('LOSS_REPORT', 'Báo cáo hao hụt'), ('AUDIT_REPORT', 'Báo cáo kiểm kê'), ('DISCREPANCY', 'Báo cáo chênh lệch kho')], db_index=True, max_length=20)),
                        ('export_format', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('PDF', 'PDF')], max_length=5)),
                        ('exported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('filter_params', models.JSONField(blank=True, default=dict)),
                        ('row_count', models.IntegerField(default=0)),
                        ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Nhật ký xuất báo cáo',
                        'verbose_name_plural': 'Nhật ký xuất báo cáo',
                        'db_table': 'report_export_logs',
                        'ordering': ['-exported_at'],
                        'indexes': [models.Index(fields=['report_type', 'exported_at'], name='idx_exportlog_type_date'), models.Index(fields=['exported_by'], name='idx_exportlog_user')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
