# Generated by Django 6.0.4 on 2026-04-13 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Tên đầy đủ, tối thiểu 2 ký tự', max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Số điện thoại phải có 10-11 chữ số', regex='^[0-9]{10,11}$')]),
        ),
    ]
